[ -f "$HOME/.config/shell/env.sh" ] && . "$HOME/.config/shell/env.sh"

case $- in
    *i*)
        ;;
    *)
        return 0
        ;;
esac

[ -f "$HOME/.fzf.bash" ] && . "$HOME/.fzf.bash"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
