[ -f "$HOME/.config/shell/env.sh" ] && . "$HOME/.config/shell/env.sh"

case $- in
    *i*)
        ;;
    *)
        return 0
        ;;
esac

if command -v sheldon >/dev/null 2>&1; then
    eval "$(sheldon source)"
fi

[ -f "$HOME/.fzf.zsh" ] && . "$HOME/.fzf.zsh"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
bindkey -M viins '^X^E' edit-command-line
bindkey -M vicmd '^X^E' edit-command-line
